-- id                               int                              声音ID
-- resouce                          string                           资源名字
-- restype                          int                              类型(1:bgm;2:effect)
-- sencetype                        int                              应用场景(0:通用;1:登陆;2:大厅;3:斗地主;4:扎金花;5:斗牛)(用以区别路径)
-- effecttype                       int                              类型（1通用效果音 2：男女效果）
-- remarks                          string                           备注

return {
	[1] = {
		resouce = "Default_Dajiahao",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "大家一起浪起来",
	},
	[2] = {
		resouce = "Default_Buhaoyisi",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "一点小钱，那都不是事",
	},
	[3] = {
		resouce = "Default_Buyaozou",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "不要走,决战到天亮",
	},
	[4] = {
		resouce = "Default_Kuaidian",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "快点啊,等得花儿都谢了",
	},
	[5] = {
		resouce = "Default_Fengshui",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "风水轮流转,底裤都输光了",
	},
	[6] = {
		resouce = "Default_Jingran",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "竟然被看穿了,你真厉害",
	},
	[7] = {
		resouce = "Default_Kanwo",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "看我通杀全场,这些钱都是我的",
	},
	[8] = {
		resouce = "Default_Dipai",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "底牌亮出来,绝对吓死你",
	},
	[9] = {
		resouce = "Default_Kuaidianxia",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "快点下注吧,一会儿就没机会了",
	},
	[10] = {
		resouce = "Default_Woshizhuang",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "我是庄家,谁敢挑战我",
	},
	[11] = {
		resouce = "Default_Wozaojiu",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "我早就看穿你的牌了",
	},
	[12] = {
		resouce = "Default_Zaijian",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "大牛吃小牛，不要伤心哟",
	},
	[13] = {
		resouce = "Default_Zenmeyou",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "你真是一个天生的演员",
	},
	[14] = {
		resouce = "sound_fapai",
		restype = 2,
		sencetype = 5,
		effecttype = 1,
		remarks = "发牌",
	},
	[15] = {
		resouce = "getCoin",
		restype = 2,
		sencetype = 5,
		effecttype = 1,
		remarks = "获得金币",
	},
	[16] = {
		resouce = "zhadan",
		restype = 2,
		sencetype = 5,
		effecttype = 1,
		remarks = "炸弹",
	},
	[17] = {
		resouce = "pijiu",
		restype = 2,
		sencetype = 5,
		effecttype = 1,
		remarks = "啤酒",
	},
	[18] = {
		resouce = "xianhua",
		restype = 2,
		sencetype = 5,
		effecttype = 1,
		remarks = "鲜花",
	},
	[19] = {
		resouce = "m_wen",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "吻",
	},
	[64] = {
		resouce = "music-login-bg",
		restype = 1,
		sencetype = 0,
		effecttype = 0,
		remarks = "登录+大厅背景音乐",
	},
	[65] = {
		resouce = "card_click",
		restype = 2,
		sencetype = 0,
		effecttype = 0,
		remarks = "按钮点击声音",
	},
	[87] = {
		resouce = "gaming_room_bg",
		restype = 1,
		sencetype = 5,
		effecttype = 1,
		remarks = "斗牛牛房间背景音乐",
	},
	[88] = {
		resouce = "game_start_music",
		restype = 2,
		sencetype = 5,
		effecttype = 1,
		remarks = "游戏开始音效",
	},
	[89] = {
		resouce = "lose",
		restype = 2,
		sencetype = 5,
		effecttype = 1,
		remarks = "游戏失败音效",
	},
	[90] = {
		resouce = "moving_chips_music",
		restype = 2,
		sencetype = 5,
		effecttype = 1,
		remarks = "下注音效",
	},
	[91] = {
		resouce = "wait_bet_music",
		restype = 2,
		sencetype = 5,
		effecttype = 1,
		remarks = "闲家等待音效",
	},
	[92] = {
		resouce = "zhuang_wait_bet_music",
		restype = 2,
		sencetype = 5,
		effecttype = 1,
		remarks = "庄家等待音效",
	},
	[93] = {
		resouce = "niu_type0_1",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "没牛音效1",
	},
	[94] = {
		resouce = "niu_type0_2",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "没牛音效2",
	},
	[95] = {
    		resouce = "M_zhadan",
    		restype = 2,
    		sencetype = 5,
    		effecttype = 2,
    		remarks = "炸弹说",
    	},
    [96] = {
        resouce = "M_pijiu",
        restype = 2,
        sencetype = 5,
        effecttype = 2,
        remarks = "说啤酒",
    },
    [97] = {
        resouce = "M_xianhua",
        restype = 2,
        sencetype = 5,
        effecttype = 2,
        remarks = "说鲜花",
    },
    [98] = {
        resouce = "M_kiss",
        restype = 2,
        sencetype = 5,
        effecttype = 2,
        remarks = "说吻",
    },
    [99] = {
        resouce = "random_banker_lianxu",
        restype = 2,
        sencetype = 5,
        effecttype = 1,
        remarks = "抢庄音效",
    },
    [100] = {
        resouce = "sit",
        restype = 2,
        sencetype = 5,
        effecttype = 1,
        remarks = "坐下音效",
    },
    [101] = {
        resouce = "daojishi",
        restype = 2,
        sencetype = 5,
        effecttype = 1,
        remarks = "倒计时音效",
    },
    [102] = {
        resouce = "win",
        restype = 2,
        sencetype = 5,
        effecttype = 1,
        remarks = "赢了音效",
    },
	[130] = {
		resouce = "niu_type1",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "牛1",
	},
	[131] = {
		resouce = "niu_type2",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "牛2",
	},
	[132] = {
		resouce = "niu_type3",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "牛3",
	},
	[133] = {
		resouce = "niu_type4",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "牛4",
	},
	[134] = {
		resouce = "niu_type5",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "牛5",
	},
	[135] = {
		resouce = "niu_type6",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "牛6",
	},
	[136] = {
		resouce = "niu_type7",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "牛7",
	},
	[137] = {
		resouce = "niu_type8",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "牛8",
	},
	[138] = {
		resouce = "niu_type9",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "牛9",
	},
	[139] = {
		resouce = "niu_type10",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "牛牛",
	},
	[140] = {
		resouce = "niu_type11",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "对子牛",
	},
	[141] = {
    		resouce = "niu_type12",
    		restype = 2,
    		sencetype = 5,
    		effecttype = 2,
    		remarks = "顺子牛",
    	},
	[142] = {
		resouce = "niu_type13",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "五花牛",
	},
	[143] = {
		resouce = "niu_type14",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "同花牛",
	},
	[144] = {
		resouce = "niu_type15",
		restype = 2,
		sencetype = 5,
		effecttype = 2,
		remarks = "葫芦牛",
	},
	[145] = {
        resouce = "niu_type16",
        restype = 2,
        sencetype = 5,
        effecttype = 2,
        remarks = "炸弹牛",
    },
    [146] = {
        resouce = "niu_type17",
        restype = 2,
        sencetype = 5,
        effecttype = 2,
        remarks = "快乐牛",
     }
}